name: Online Editor API

on:
  repository_dispatch:
    types: [update_file]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update file from payload
        env:
          FILE_PATH: ${{ github.event.client_payload.file }}
          CONTENT: ${{ github.event.client_payload.content }}
        run: |
          echo "Decoding base64 and updating $FILE_PATH"
          echo "$CONTENT" | base64 --decode > "$FILE_PATH"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "$FILE_PATH"
          git commit -m "在线编辑器更新文件 $(date +'%Y-%m-%d %H:%M:%S')" || echo "无变更"
          git push
